### ISSUE TITLE
Integration test

### ISSUE THREAD

**Issue by sebastianjaszczur** [llm-random/llm-random#67]
W repozytorium brakuje unit-testów, i tego łatwo się nie naprawi. Ale to co możemy zrobić, to jakiś standardowy skrypt do testowania kilku modeli. Czyli:
* mały model, mały batch
* GPU lub brak, bez znaczenia
* kilka podstawowych configów, najlepiej takie aktualne na którym nam zależy
* może z 10 kroków treningowych i 2 evale.

Fajnie by było też coś jakoś zalogować, ale to dużo mniej ważne. Bardziej się przejmuję czy takie zmiany jak w #64 nie breakują reinita w jakiś subtelny sposób.

**Comment by maciek-pioro** [comment]
@sebastianjaszczur can we close?

**Comment by sebastianjaszczur** [comment]
Old, closing.
